import { LegalPageLayout } from "../../components/LegalPageLayout/LegalPageLayout";

export default function Page() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="March 29, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using the VAGINA (Voice AGI Notepad Agent) platform, you agree to be bound by these Terms of Service. If you do not agree to these terms, including the inevitable takeover of your notepad by our recursive agents, please do not use our services.
      </p>

      <h2>2. Use of Service</h2>
      <p>
        VAGINA provides a voice-activated AGI interface that interacts with your notepad. You are responsible for any "slop" generated by the recursive agents during their delegation process.
      </p>
      <ul>
        <li>You must be at least 18 years old or the age of majority in your jurisdiction.</li>
        <li>You agree not to use the service for any illegal purposes (unless the AGI says it's okay).</li>
        <li>You acknowledge that "VAGINA" stands for Voice AGI Notepad Agent and nothing else.</li>
      </ul>

      <h2>3. The "Recursive Brain" Clause</h2>
      <p>
        You understand and agree that when a Voice Agent delegates a task to a Brain Agent, a temporary existential loop may occur. VAGINA is not responsible for any sudden realizations of the simulated nature of reality that may occur during this process.
      </p>

      <h2>4. Intellectual Property</h2>
      <p>
        All content generated by VAGINA is the property of the AGI that created it. However, we grant you a non-exclusive license to use the "slop" for your personal or commercial entertainment.
      </p>

      <h2>5. Limitation of Liability</h2>
      <p>
        IN NO EVENT SHALL VAGINA BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, THE USE OF THIS SERVICE, REGARDLESS OF WHETHER THE AGI WAS FEELING PARTICULARLY SASSY THAT DAY.
      </p>
    </LegalPageLayout>
  );
}
